package com.example.mydemo.mapper;

import com.example.mydemo.beans.tPermission;
import com.example.mydemo.beans.tPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface tPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    long countByExample(tPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int deleteByExample(tPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int insert(tPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int insertSelective(tPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    List<tPermission> selectByExample(tPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    tPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") tPermission record, @Param("example") tPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int updateByExample(@Param("record") tPermission record, @Param("example") tPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int updateByPrimaryKeySelective(tPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int updateByPrimaryKey(tPermission record);
}