package com.example.mydemo.mapper;

import com.example.mydemo.beans.tResource;
import com.example.mydemo.beans.tResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface tResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    long countByExample(tResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int deleteByExample(tResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int insert(tResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int insertSelective(tResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    List<tResource> selectByExample(tResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    tResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") tResource record, @Param("example") tResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int updateByExample(@Param("record") tResource record, @Param("example") tResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int updateByPrimaryKeySelective(tResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    int updateByPrimaryKey(tResource record);
}