package com.example.mydemo.beans;

import java.util.Date;

public class tPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.permission_name
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private String permissionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.permission_lable
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private String permissionLable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.create_time
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.update_time
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.create_by_id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private Long createById;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.update_by_id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private Long updateById;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.counts
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private Long counts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.delete_flg
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private String deleteFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public tPermission(Long id, String permissionName, String permissionLable, Date createTime, Date updateTime, Long createById, Long updateById, Long counts, String deleteFlg) {
        this.id = id;
        this.permissionName = permissionName;
        this.permissionLable = permissionLable;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.createById = createById;
        this.updateById = updateById;
        this.counts = counts;
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public tPermission() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.id
     *
     * @return the value of t_permission.id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.id
     *
     * @param id the value for t_permission.id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.permission_name
     *
     * @return the value of t_permission.permission_name
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.permission_name
     *
     * @param permissionName the value for t_permission.permission_name
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.permission_lable
     *
     * @return the value of t_permission.permission_lable
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public String getPermissionLable() {
        return permissionLable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.permission_lable
     *
     * @param permissionLable the value for t_permission.permission_lable
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setPermissionLable(String permissionLable) {
        this.permissionLable = permissionLable == null ? null : permissionLable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.create_time
     *
     * @return the value of t_permission.create_time
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.create_time
     *
     * @param createTime the value for t_permission.create_time
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.update_time
     *
     * @return the value of t_permission.update_time
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.update_time
     *
     * @param updateTime the value for t_permission.update_time
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.create_by_id
     *
     * @return the value of t_permission.create_by_id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public Long getCreateById() {
        return createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.create_by_id
     *
     * @param createById the value for t_permission.create_by_id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setCreateById(Long createById) {
        this.createById = createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.update_by_id
     *
     * @return the value of t_permission.update_by_id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public Long getUpdateById() {
        return updateById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.update_by_id
     *
     * @param updateById the value for t_permission.update_by_id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setUpdateById(Long updateById) {
        this.updateById = updateById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.counts
     *
     * @return the value of t_permission.counts
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public Long getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.counts
     *
     * @param counts the value for t_permission.counts
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setCounts(Long counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.delete_flg
     *
     * @return the value of t_permission.delete_flg
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public String getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.delete_flg
     *
     * @param deleteFlg the value for t_permission.delete_flg
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setDeleteFlg(String deleteFlg) {
        this.deleteFlg = deleteFlg == null ? null : deleteFlg.trim();
    }
}