package com.example.mydemo.beans;

import java.util.Date;

public class tResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.id
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.resource_name
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    private String resourceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.resource_lable
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    private String resourceLable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.create_time
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.update_time
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.create_by_id
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    private Long createById;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.update_by_id
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    private Long updateById;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.counts
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    private Long counts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_resource.delete_flg
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    private String deleteFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public tResource(Long id, String resourceName, String resourceLable, Date createTime, Date updateTime, Long createById, Long updateById, Long counts, String deleteFlg) {
        this.id = id;
        this.resourceName = resourceName;
        this.resourceLable = resourceLable;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.createById = createById;
        this.updateById = updateById;
        this.counts = counts;
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_resource
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public tResource() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.id
     *
     * @return the value of t_resource.id
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.id
     *
     * @param id the value for t_resource.id
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.resource_name
     *
     * @return the value of t_resource.resource_name
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public String getResourceName() {
        return resourceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.resource_name
     *
     * @param resourceName the value for t_resource.resource_name
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public void setResourceName(String resourceName) {
        this.resourceName = resourceName == null ? null : resourceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.resource_lable
     *
     * @return the value of t_resource.resource_lable
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public String getResourceLable() {
        return resourceLable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.resource_lable
     *
     * @param resourceLable the value for t_resource.resource_lable
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public void setResourceLable(String resourceLable) {
        this.resourceLable = resourceLable == null ? null : resourceLable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.create_time
     *
     * @return the value of t_resource.create_time
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.create_time
     *
     * @param createTime the value for t_resource.create_time
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.update_time
     *
     * @return the value of t_resource.update_time
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.update_time
     *
     * @param updateTime the value for t_resource.update_time
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.create_by_id
     *
     * @return the value of t_resource.create_by_id
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public Long getCreateById() {
        return createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.create_by_id
     *
     * @param createById the value for t_resource.create_by_id
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public void setCreateById(Long createById) {
        this.createById = createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.update_by_id
     *
     * @return the value of t_resource.update_by_id
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public Long getUpdateById() {
        return updateById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.update_by_id
     *
     * @param updateById the value for t_resource.update_by_id
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public void setUpdateById(Long updateById) {
        this.updateById = updateById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.counts
     *
     * @return the value of t_resource.counts
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public Long getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.counts
     *
     * @param counts the value for t_resource.counts
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public void setCounts(Long counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_resource.delete_flg
     *
     * @return the value of t_resource.delete_flg
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public String getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_resource.delete_flg
     *
     * @param deleteFlg the value for t_resource.delete_flg
     *
     * @mbg.generated Tue Oct 23 14:06:18 CST 2018
     */
    public void setDeleteFlg(String deleteFlg) {
        this.deleteFlg = deleteFlg == null ? null : deleteFlg.trim();
    }
}