package com.example.mydemo.beans;

import java.util.Date;

public class tRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role_name
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.create_time
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.update_time
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.create_by_id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private Long createById;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.update_by_id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private Long updateById;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.counts
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private Long counts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.delete_flg
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    private String deleteFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public tRole(Long id, String roleName, Date createTime, Date updateTime, Long createById, Long updateById, Long counts, String deleteFlg) {
        this.id = id;
        this.roleName = roleName;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.createById = createById;
        this.updateById = updateById;
        this.counts = counts;
        this.deleteFlg = deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public tRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.id
     *
     * @return the value of t_role.id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.id
     *
     * @param id the value for t_role.id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role_name
     *
     * @return the value of t_role.role_name
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role_name
     *
     * @param roleName the value for t_role.role_name
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.create_time
     *
     * @return the value of t_role.create_time
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.create_time
     *
     * @param createTime the value for t_role.create_time
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.update_time
     *
     * @return the value of t_role.update_time
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.update_time
     *
     * @param updateTime the value for t_role.update_time
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.create_by_id
     *
     * @return the value of t_role.create_by_id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public Long getCreateById() {
        return createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.create_by_id
     *
     * @param createById the value for t_role.create_by_id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setCreateById(Long createById) {
        this.createById = createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.update_by_id
     *
     * @return the value of t_role.update_by_id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public Long getUpdateById() {
        return updateById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.update_by_id
     *
     * @param updateById the value for t_role.update_by_id
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setUpdateById(Long updateById) {
        this.updateById = updateById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.counts
     *
     * @return the value of t_role.counts
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public Long getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.counts
     *
     * @param counts the value for t_role.counts
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setCounts(Long counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.delete_flg
     *
     * @return the value of t_role.delete_flg
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public String getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.delete_flg
     *
     * @param deleteFlg the value for t_role.delete_flg
     *
     * @mbg.generated Mon Nov 05 13:52:23 CST 2018
     */
    public void setDeleteFlg(String deleteFlg) {
        this.deleteFlg = deleteFlg == null ? null : deleteFlg.trim();
    }
}