package com.example.mydemo.beans;

import java.util.Date;

public class tUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.user_id
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.role_id
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.create_time
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.update_time
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.create_by_id
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    private Long createById;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.update_by_id
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    private Long updateById;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.counts
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    private Long counts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.delete_flg
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    private String deleteFlg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.user_id
     *
     * @return the value of t_user_role.user_id
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.user_id
     *
     * @param userId the value for t_user_role.user_id
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.role_id
     *
     * @return the value of t_user_role.role_id
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.role_id
     *
     * @param roleId the value for t_user_role.role_id
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.create_time
     *
     * @return the value of t_user_role.create_time
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.create_time
     *
     * @param createTime the value for t_user_role.create_time
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.update_time
     *
     * @return the value of t_user_role.update_time
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.update_time
     *
     * @param updateTime the value for t_user_role.update_time
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.create_by_id
     *
     * @return the value of t_user_role.create_by_id
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public Long getCreateById() {
        return createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.create_by_id
     *
     * @param createById the value for t_user_role.create_by_id
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public void setCreateById(Long createById) {
        this.createById = createById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.update_by_id
     *
     * @return the value of t_user_role.update_by_id
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public Long getUpdateById() {
        return updateById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.update_by_id
     *
     * @param updateById the value for t_user_role.update_by_id
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public void setUpdateById(Long updateById) {
        this.updateById = updateById;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.counts
     *
     * @return the value of t_user_role.counts
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public Long getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.counts
     *
     * @param counts the value for t_user_role.counts
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public void setCounts(Long counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.delete_flg
     *
     * @return the value of t_user_role.delete_flg
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public String getDeleteFlg() {
        return deleteFlg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.delete_flg
     *
     * @param deleteFlg the value for t_user_role.delete_flg
     *
     * @mbg.generated Sun Sep 23 22:37:22 CST 2018
     */
    public void setDeleteFlg(String deleteFlg) {
        this.deleteFlg = deleteFlg == null ? null : deleteFlg.trim();
    }
}